FROM alpine_base

# https://github.com/Tencent/Tars/blob/master/Install.md

MAINTAINER Bolik WaterBolik@163.com

RUN set -x \	
	&& apk add --update --no-cache \
        glib-dev \
        cmake \

    && echo "end"


# $ docker build -t tars /Volumes/Work/OpenSource/WaterBolik/prestudy/bdocker/tars/
# docker build -t tars B:/OpenSource/WaterBolik/prestudy/bdocker/tars/
# docker run -it --rm tars 