FROM bjava

MAINTAINER Bolik WaterBolik@163.com

# hadoop 基本环节安装

RUN set -ex \
   

  && echo "end"

CMD ["bash"]

# $ docker build -t bhadoop /Volumes/Work/OpenSource/WaterBolik/prestudy/bdocker/bhadoop/.
# $ docker run -it --rm bhadoop
# docker build -t bhadoop B:\OpenSource\WaterBolik\prestudy\bdocker\bnodejs\
# docker run -it --rm bhadoop 